-- ============================================
-- 修复留言板表和策略（修复类型错误）
-- 在 Supabase SQL Editor 中运行此脚本
-- ============================================

-- 1. 删除表（如果存在）
DROP TABLE IF EXISTS message_replies CASCADE;
DROP TABLE IF EXISTS message_likes CASCADE;
DROP TABLE IF EXISTS messages CASCADE;

-- 2. 创建留言表
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    user_nickname TEXT NOT NULL,
    user_avatar TEXT DEFAULT '🧙',
    content TEXT NOT NULL,
    is_guest BOOLEAN DEFAULT false,
    likes_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 创建点赞表
CREATE TABLE message_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL,
    is_guest_liker BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(message_id, user_id)
);

-- 4. 创建回复表
CREATE TABLE message_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id UUID,
    user_nickname TEXT NOT NULL,
    user_avatar TEXT DEFAULT '🧙',
    content TEXT NOT NULL,
    is_guest BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. 创建索引
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_message_likes_message_id ON message_likes(message_id);
CREATE INDEX IF NOT EXISTS idx_message_likes_user_id ON message_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_message_replies_message_id ON message_replies(message_id);
CREATE INDEX IF NOT EXISTS idx_message_replies_created_at ON message_replies(created_at);

-- 6. 创建触发器函数
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE OR REPLACE FUNCTION update_likes_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE messages SET likes_count = likes_count + 1 WHERE id = NEW.message_id;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE messages SET likes_count = likes_count - 1 WHERE id = OLD.message_id;
        RETURN OLD;
    END IF;
END;
$$ language 'plpgsql';

-- 7. 创建触发器
DROP TRIGGER IF EXISTS update_messages_updated_at ON messages;
CREATE TRIGGER update_messages_updated_at
    BEFORE UPDATE ON messages
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_message_likes_count ON message_likes;
CREATE TRIGGER update_message_likes_count
    AFTER INSERT OR DELETE ON message_likes
    FOR EACH ROW
    EXECUTE FUNCTION update_likes_count();

-- 8. 设置 RLS
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_replies ENABLE ROW LEVEL SECURITY;

-- 9. 创建 RLS 策略

-- messages 表策略
CREATE POLICY "允许所有人读取留言"
    ON messages FOR SELECT
    USING (true);

CREATE POLICY "允许插入留言"
    ON messages FOR INSERT
    WITH CHECK (
        auth.uid() = user_id OR (is_guest = true AND user_id IS NULL)
    );

CREATE POLICY "允许删除自己的留言"
    ON messages FOR DELETE
    USING (
        auth.uid() = user_id OR (is_guest = true)
    );

-- message_likes 表策略
CREATE POLICY "允许所有人读取点赞"
    ON message_likes FOR SELECT
    USING (true);

CREATE POLICY "允许点赞"
    ON message_likes FOR INSERT
    WITH CHECK (
        is_guest_liker = true
    );

CREATE POLICY "允许取消点赞"
    ON message_likes FOR DELETE
    USING (true);

-- message_replies 表策略
CREATE POLICY "允许所有人读取回复"
    ON message_replies FOR SELECT
    USING (true);

CREATE POLICY "允许插入回复"
    ON message_replies FOR INSERT
    WITH CHECK (
        auth.uid() = user_id OR (is_guest = true AND user_id IS NULL)
    );

CREATE POLICY "允许删除自己的回复"
    ON message_replies FOR DELETE
    USING (
        auth.uid() = user_id OR (is_guest = true)
    );

-- 10. 插入测试数据
INSERT INTO messages (user_nickname, user_avatar, content, is_guest) VALUES
    ('赫敏·格兰杰', '👩‍🦰', '欢迎来到霍格沃茨留言板！记得遵守礼仪哦！', false),
    ('哈利·波特', '👓⚡', '有什么问题可以在这里提问，大家会帮助你的！', false),
    ('罗恩·韦斯莱', '🧑‍🦰', '别忘了去看看三把扫帚的黄油啤酒！🍺', false);

-- 完成！
SELECT '留言板表和策略已重新创建！' as status;
