-- ============================================
-- 留言板数据库表设置 SQL
-- ============================================
-- 在 Supabase SQL Editor 中执行此脚本

-- 1. 删除旧表（如果存在）
DROP TABLE IF EXISTS message_likes CASCADE;
DROP TABLE IF EXISTS messages CASCADE;

-- 2. 创建留言表
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    user_nickname TEXT NOT NULL,
    user_avatar TEXT DEFAULT '🧙',
    content TEXT NOT NULL,
    is_guest BOOLEAN DEFAULT false,
    likes_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 创建点赞表
CREATE TABLE message_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL, -- 游客用设备ID，登录用户用userId
    is_guest_liker BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(message_id, user_id) -- 防止重复点赞
);

-- 4. 创建索引
CREATE INDEX idx_messages_created_at ON messages(created_at DESC);
CREATE INDEX idx_message_likes_message_id ON message_likes(message_id);
CREATE INDEX idx_message_likes_user_id ON message_likes(user_id);

-- 5. 创建更新时间戳触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_messages_updated_at
    BEFORE UPDATE ON messages
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 6. 创建更新点赞数的触发器
CREATE OR REPLACE FUNCTION update_likes_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE messages SET likes_count = likes_count + 1 WHERE id = NEW.message_id;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE messages SET likes_count = likes_count - 1 WHERE id = OLD.message_id;
        RETURN OLD;
    END IF;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_message_likes_count
    AFTER INSERT OR DELETE ON message_likes
    FOR EACH ROW
    EXECUTE FUNCTION update_likes_count();

-- 7. 设置 Row Level Security (RLS)
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_likes ENABLE ROW LEVEL SECURITY;

-- 8. 创建 RLS 策略

-- messages 表策略
-- 允许所有人读取留言
CREATE POLICY "允许所有人读取留言"
    ON messages FOR SELECT
    USING (true);

-- 允许登录用户插入留言
CREATE POLICY "允许登录用户插入留言"
    ON messages FOR INSERT
    WITH CHECK (auth.uid()::text = user_id);

-- 允许登录用户删除自己的留言
CREATE POLICY "允许用户删除自己的留言"
    ON messages FOR DELETE
    USING (auth.uid()::text = user_id);

-- 允许游客插入留言（user_id 为 null）
CREATE POLICY "允许游客插入留言"
    ON messages FOR INSERT
    WITH CHECK (is_guest = true AND user_id IS NULL);

-- 游客不能删除留言（即使是自己发的）
-- 因为没有 user_id 无法验证身份

-- message_likes 表策略
-- 允许所有人读取点赞记录
CREATE POLICY "允许所有人读取点赞"
    ON message_likes FOR SELECT
    USING (true);

-- 允许登录用户点赞
CREATE POLICY "允许登录用户点赞"
    ON message_likes FOR INSERT
    WITH CHECK (auth.uid()::text = user_id);

-- 允许游客点赞
CREATE POLICY "允许游客点赞"
    ON message_likes FOR INSERT
    WITH CHECK (is_guest_liker = true);

-- 允许用户取消自己的点赞
CREATE POLICY "允许用户取消点赞"
    ON message_likes FOR DELETE
    USING (true); -- 简化处理，允许任何人取消点赞（前端会控制）

-- 9. 插入一些测试数据（可选）
INSERT INTO messages (user_nickname, user_avatar, content, is_guest) VALUES
    ('赫敏·格兰杰', '👩‍🦰', '欢迎来到霍格沃茨留言板！记得遵守礼仪哦！', false),
    ('哈利·波特', '👓⚡', '有什么问题可以在这里提问，大家会帮助你的！', false),
    ('罗恩·韦斯莱', '🧑‍🦰', '别忘了去看看三把扫帚的黄油啤酒！🍺', false);

-- 完成！
